# Generated by Django 5.1.5 on 2025-12-10 12:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPServerConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the server', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('server_type', models.CharField(choices=[('stdio', 'Standard I/O'), ('sse', 'Server-Sent Events'), ('http', 'HTTP/REST')], default='stdio', help_text='Type of MCP server connection', max_length=10)),
                ('command', models.CharField(blank=True, help_text="Command to run for stdio servers (e.g., 'node server.js')", max_length=500, null=True)),
                ('url', models.URLField(blank=True, help_text='URL for HTTP/SSE servers', null=True)),
                ('args', models.JSONField(blank=True, default=list, help_text='Command arguments as JSON array')),
                ('env_vars', models.JSONField(blank=True, default=dict, help_text='Environment variables as JSON object')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this server is currently enabled')),
                ('auto_connect', models.BooleanField(default=True, help_text='Automatically connect on app startup')),
                ('require_approval', models.BooleanField(default=False, help_text='Require user approval before executing tools')),
                ('timeout', models.IntegerField(default=30, help_text='Connection timeout in seconds')),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('connection_status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error'), ('connecting', 'Connecting')], default='disconnected', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mcp_server_configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MCPResource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_uri', models.CharField(help_text='URI or identifier for the resource', max_length=500)),
                ('resource_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('resource_type', models.CharField(blank=True, help_text="Type of resource (e.g., 'file', 'database', 'api')", max_length=100, null=True)),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the resource content', max_length=100, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('access_count', models.IntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='mcpserver.mcpserverconfig')),
            ],
            options={
                'db_table': 'mcp_resources',
                'ordering': ['resource_name'],
            },
        ),
        migrations.CreateModel(
            name='MCPPrompt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prompt_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('prompt_template', models.TextField(blank=True, help_text='The actual prompt template text', null=True)),
                ('arguments', models.JSONField(default=list, help_text='List of argument definitions for the prompt')),
                ('is_enabled', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='mcpserver.mcpserverconfig')),
            ],
            options={
                'db_table': 'mcp_prompts',
                'ordering': ['prompt_name'],
            },
        ),
        migrations.CreateModel(
            name='MCPTool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('input_schema', models.JSONField(default=dict, help_text='JSON Schema for tool input parameters')),
                ('is_enabled', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('average_execution_time', models.FloatField(default=0.0, help_text='Average execution time in seconds')),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='mcpserver.mcpserverconfig')),
            ],
            options={
                'db_table': 'mcp_tools',
                'ordering': ['tool_name'],
            },
        ),
        migrations.CreateModel(
            name='MCPExecutionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tool_name', models.CharField(help_text='Tool name for reference', max_length=255)),
                ('server_name', models.CharField(help_text='Server name for reference', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('input_params', models.JSONField(default=dict)),
                ('output_result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time', models.FloatField(default=0.0, help_text='Execution time in seconds')),
                ('chat_thread_id', models.CharField(blank=True, help_text='Associated chat thread if executed from chat', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_executions', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='mcpserver.mcptool')),
            ],
            options={
                'db_table': 'mcp_execution_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mcpserverconfig',
            index=models.Index(fields=['user', 'is_active'], name='mcp_server__user_id_dbf5cd_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpserverconfig',
            index=models.Index(fields=['connection_status'], name='mcp_server__connect_170dd8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mcpserverconfig',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='mcpresource',
            index=models.Index(fields=['server_config', 'is_enabled'], name='mcp_resourc_server__1522c4_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpresource',
            index=models.Index(fields=['resource_type'], name='mcp_resourc_resourc_fe8b34_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mcpresource',
            unique_together={('server_config', 'resource_uri')},
        ),
        migrations.AddIndex(
            model_name='mcpprompt',
            index=models.Index(fields=['server_config', 'is_enabled'], name='mcp_prompts_server__5e6f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpprompt',
            index=models.Index(fields=['prompt_name'], name='mcp_prompts_prompt__14feb1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mcpprompt',
            unique_together={('server_config', 'prompt_name')},
        ),
        migrations.AddIndex(
            model_name='mcptool',
            index=models.Index(fields=['server_config', 'is_enabled'], name='mcp_tools_server__6abe71_idx'),
        ),
        migrations.AddIndex(
            model_name='mcptool',
            index=models.Index(fields=['tool_name'], name='mcp_tools_tool_na_89ccf7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mcptool',
            unique_together={('server_config', 'tool_name')},
        ),
        migrations.AddIndex(
            model_name='mcpexecutionlog',
            index=models.Index(fields=['user', 'status'], name='mcp_executi_user_id_d5c47c_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpexecutionlog',
            index=models.Index(fields=['tool', 'status'], name='mcp_executi_tool_id_1b00b1_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpexecutionlog',
            index=models.Index(fields=['created_at'], name='mcp_executi_created_0155a7_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpexecutionlog',
            index=models.Index(fields=['chat_thread_id'], name='mcp_executi_chat_th_101cb3_idx'),
        ),
    ]
