# Generated by Django 5.2.4 on 2025-09-19 09:35

from django.db import migrations


def create_default_subscription_plans(apps, schema_editor):
    """Create default subscription plans"""
    SubscriptionPlan = apps.get_model('authentication', 'SubscriptionPlan')
    
    plans = [
        {
            "name": "Free",
            "description": "Free tier with basic features",
            "price": 0.00,
            "duration_days": 30,
            "max_requests": 20
        },
        {
            "name": "Plus",
            "description": "Plus tier with enhanced features",
            "price": 9.99,
            "duration_days": 30,
            "max_requests": 100
        },
        {
            "name": "Pro",
            "description": "Professional tier with premium features",
            "price": 19.99,
            "duration_days": 30,
            "max_requests": 200
        },
    ]
    
    for plan_data in plans:
        # Check if plan already exists to avoid duplicates
        if not SubscriptionPlan.objects.filter(name=plan_data["name"]).exists():
            SubscriptionPlan.objects.create(**plan_data)


def reverse_create_default_subscription_plans(apps, schema_editor):
    """Remove default subscription plans"""
    SubscriptionPlan = apps.get_model('authentication', 'SubscriptionPlan')
    
    plan_names = ["Free", "Plus", "Pro"]
    SubscriptionPlan.objects.filter(name__in=plan_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_default_subscription_plans,
            reverse_create_default_subscription_plans
        ),
    ]
