# Generated by Django 5.2.4 on 2025-09-19 09:37

from django.db import migrations
from django.contrib.auth.hashers import make_password
import os


def create_admin_user(apps, schema_editor):
    """Create admin user with environment variables or defaults."""
    User = apps.get_model('authentication', 'User')
    SubscriptionPlan = apps.get_model('authentication', 'SubscriptionPlan')
    
    # Get admin credentials from environment variables or use defaults
    admin_email = os.getenv('ADMIN_EMAIL', 'admin@cognivox.com')
    admin_username = os.getenv('ADMIN_USERNAME', 'admin')
    admin_password = os.getenv('ADMIN_PASSWORD', 'admin123')
    
    # Check if admin user already exists
    if not User.objects.filter(email=admin_email).exists():
        # Get the Pro subscription plan (assuming it exists from previous migration)
        try:
            pro_plan = SubscriptionPlan.objects.get(name='Pro')
        except SubscriptionPlan.DoesNotExist:
            # Fallback to any available plan
            pro_plan = SubscriptionPlan.objects.first()
        
        # Create admin user
        admin_user = User.objects.create(
            email=admin_email,
            username=admin_username,
            password=make_password(admin_password),
            is_staff=True,
            is_superuser=True,
            is_active=True,
            role='ADMIN',
            subscription_plan=pro_plan
        )
        print(f"Created admin user: {admin_email}")
    else:
        print(f"Admin user {admin_email} already exists")


def reverse_create_admin_user(apps, schema_editor):
    """Remove admin user."""
    User = apps.get_model('authentication', 'User')
    
    # Get admin email from environment or use default
    admin_email = os.getenv('ADMIN_EMAIL', 'admin@cognivox.com')
    
    # Remove admin user
    User.objects.filter(email=admin_email).delete()
    print(f"Removed admin user: {admin_email}")


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_add_default_subscription_plans"),
    ]

    operations = [
        migrations.RunPython(
            create_admin_user,
            reverse_create_admin_user,
        ),
    ]
