# Generated by Django 5.2.4 on 2025-09-24 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsubthread",
            name="answer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatsubthread",
            name="chat_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="chatsubthread",
            name="execution_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatsubthread",
            name="n_results",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="chatsubthread",
            name="query",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatsubthread",
            name="related_links",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="chatsubthread",
            name="response_mode",
            field=models.CharField(default="general", max_length=50),
        ),
        migrations.AddField(
            model_name="chatsubthread",
            name="sources",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="chatsubthread",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
