# Generated by Django 5.2.4 on 2025-10-07 05:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_remove_model_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatthread",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Space",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("color", models.CharField(default="#6366f1", max_length=7)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "spaces",
                "ordering": ["-created_at"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.AddField(
            model_name="chatthread",
            name="space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="threads",
                to="chat.space",
            ),
        ),
    ]
