# Generated by Django 5.1.5 on 2025-11-12 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_convert_to_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="chatsubthread",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="chatsubthreadmessage",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="chatthread",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
